name: rtm
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - gmt>=6.1.0  # Because 6.1.0 fixes some PyGMT-relevant bugs
  - ipython
  - obspy
  - pip
  - pygmt
  - utm
  - xarray
  - pip:
    - git+https://github.com/uafgeotools/waveform_collection.git
    - -e .
